version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
      - ./vote:/app
    ports:
      - "5000:80"
    environment:
      - VIRTUAL_HOST: ${VOTE_HOST}
      - LETSENCRYPT_HOST: ${VOTE_HOST}

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    build: ./worker

  db:
    image: postgres:9.4

  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    environment:
      - VIRTUAL_HOST: ${RESULT_HOST}
      - LETSENCRYPT_HOST: ${RESULT_HOST}
